name: fetch

on:
  push:
    branches:
      - main
    paths:
      - "fetch/**"
  pull_request:
    branches:
      - main
    paths:
      - "fetch/**"
      - ".github/workflows/fetch.yml"

jobs:
  check:
    name: Typecheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16
        project:
          - fetch
    steps:
      - uses: actions/checkout@v2

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        uses: bahmutov/npm-install@v1

      - name: Typecheck
        uses: gozala/typescript-error-reporter-action@v1.0.8
        with:
          project: ${{matrix.project}}/tsconfig.json

  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version:
          - 14
          - 16
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        project:
          - fetch
        exclude:
          - os: windows-latest
            node-version: 15
          # On macOS, run tests with only the LTS environments.
          - os: macos-latest
            node-version: 15

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        uses: bahmutov/npm-install@v1

      - name: Test (ESM)
        run: yarn --cwd ${{matrix.project}} test -- --colors

      # upload coverage only once
      - name: Coveralls
        uses: coverallsapp/github-action@master
        if: matrix.node == '14' && matrix.os == 'ubuntu-latest'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test (CJS)
        run: yarn --cwd ${{matrix.project}} test:cjs
  publish:
    name: Publish
    needs:
      - test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - fetch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Install
        uses: bahmutov/npm-install@v1

      - name: Build
        run: yarn --cwd ${{matrix.project}} build

      - name: Publish
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          DEPLOY_DIR: ${{matrix.project}}
          SRC_PACKAGE_DIR: ${{matrix.project}}
